In [3]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("/Users/raghav/Downloads/Modified_Threat_Level_Debit_Card_Fraud_Dataa.csv")
df

,TransactionID,AccountID,TransactionAmount,TransactionDate,TransactionType,Location,DeviceID,IP Address,MerchantID,Channel,TransactionDuration,LoginAttempts,AccountBalance,PreviousTransactionDate,Customer_ID,TimeSinceLastTransaction,Fraud,Threat Level,Threat_Level
0,TX000001,AC00128,14.09,2023-04-11 16:29:14,Debit,San Diego,D000380,162.198.218.92,M015,ATM,81,1,5112.21,2024-11-04 08:08:08,42941,-49477134.0,False,0.0,Low
1,TX000002,AC00455,376.24,2023-06-27 16:44:19,Debit,Houston,D000051,13.149.61.4,M052,ATM,141,1,13758.91,2024-11-04 08:09:35,53701,-42823516.0,False,0.0,Low
2,TX000003,AC00019,126.29,2023-07-10 18:16:08,Debit,Mesa,D000235,215.97.143.157,M009,Online,56,1,1122.35,2024-11-04 08:07:04,49104,-41694656.0,False,0.0,Low
3,TX000004,AC00070,184.50,2023-05-05 16:32:11,Debit,Raleigh,D000187,200.13.225.150,M002,Online,25,1,8569.06,2024-11-04 08:09:06,78390,-47403415.0,False,0.0,Low
4,TX000006,AC00393,92.15,2023-04-03 17:15:01,Debit,Oklahoma City,D000579,117.67.192.211,M054,ATM,172,1,781.68,2024-11-04 08:06:36,38695,-50165495.0,False,0.0,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1939,TX002506,AC00377,577.12,2023-01-27 17:38:07,Debit,Virginia Beach,D000110,120.16.186.17,M075,ATM,69,1,5265.88,2024-11-04 08:10:50,33818,-55866763.0,False,0.0,Low
1940,TX002507,AC00258,92.24,2023-04-13 17:45:33,Debit,Philadelphia,D000531,189.183.50.147,M076,Branch,93,1,6937.48,2024-11-04 08:09:06,64892,-49299813.0,False,0.0,Low
1941,TX002509,AC00322,251.54,2023-03-22 17:36:48,Debit,Tucson,D000410,49.174.157.140,M029,Branch,177,1,254.75,2024-11-04 08:11:42,32121,-51201294.0,False,0.0,Low
1942,TX002510,AC00095,28.63,2023-08-21 17:08:50,Debit,San Diego,D000095,58.1.27.124,M087,Branch,146,1,3382.91,2024-11-04 08:08:39,39761,-38069989.0,False,0.0,Low
1943,TX002511,AC00118,185.97,2023-02-24 16:24:46,Debit,Denver,D000634,21.190.11.223,M041,Online,19,1,1776.91,2024-11-04 08:12:22,10493,-53452056.0,False,0.0,Low

In [6]:
df.loc[df['Fraud'] == True, 'Threat_Level'] = df.loc[df['Fraud'] == True, 'Threat Level'].apply(
    lambda x: 'Low' if x <= 1 else ('Medium' if x in [2, 3] else 'High')
)

In [13]:
df['Fraud'] = df['Fraud'].astype(int)

In [14]:
df.loc[df['Fraud'] == True]

,TransactionID,AccountID,TransactionAmount,TransactionDate,TransactionType,Location,DeviceID,IP Address,MerchantID,Channel,TransactionDuration,LoginAttempts,AccountBalance,PreviousTransactionDate,Customer_ID,TimeSinceLastTransaction,Fraud,Threat Level,Threat_Level
14,TX000024,AC00453,345.84,2023-05-02 18:25:46,Debit,Fort Worth,D000162,191.82.103.198,M083,Online,142,3,1402.50,2024-11-04 08:07:04,87069,-47655678.0,1,2.0,Medium
16,TX000027,AC00441,246.93,2023-04-17 16:37:01,Debit,Miami,D000046,55.154.161.250,M029,ATM,158,5,673.35,2024-11-04 08:11:38,79787,-48958477.0,1,3.0,Medium
21,TX000033,AC00060,396.45,2023-09-25 16:26:00,Debit,New York,D000621,133.67.250.163,M007,ATM,168,3,9690.15,2024-11-04 08:11:13,65285,-35048713.0,1,2.0,Medium
26,TX000039,AC00478,795.31,2023-10-12 17:07:40,Debit,Mesa,D000077,49.29.37.185,M048,ATM,90,2,7914.88,2024-11-04 08:11:17,56111,-33577417.0,1,1.0,Low
52,TX000075,AC00265,1212.51,2023-10-04 16:36:29,Debit,Indianapolis,D000231,193.83.0.183,M036,Branch,24,1,605.95,2024-11-04 08:06:51,29801,-34270222.0,1,1.0,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1841,TX002373,AC00260,95.23,2023-10-16 18:47:17,Debit,Denver,D000287,5.252.94.135,M077,Online,60,3,966.88,2024-11-04 08:11:38,82601,-33225861.0,1,2.0,Medium
1863,TX002404,AC00111,1493.00,2023-06-07 17:05:41,Debit,Colorado Springs,D000344,136.162.111.135,M096,ATM,151,1,1619.16,2024-11-04 08:07:07,80702,-44550086.0,1,2.0,Medium
1879,TX002424,AC00340,332.06,2023-06-21 16:38:54,Debit,Seattle,D000365,94.37.250.128,M086,ATM,221,4,11826.52,2024-11-04 08:06:23,47806,-43342049.0,1,3.0,Medium
1895,TX002446,AC00439,403.01,2023-09-04 17:32:35,Debit,Washington,D000677,223.32.70.156,M029,Online,286,3,10513.52,2024-11-04 08:09:32,46702,-36859017.0,1,4.0,High
1903,TX002456,AC00043,655.81,2023-05-05 16:52:44,Debit,Omaha,D000567,86.83.61.143,M044,ATM,164,2,4539.99,2024-11-04 08:12:08,83419,-47402364.0,1,1.0,Low

In [16]:
df.to_csv('/Users/raghav/Downloads/Latest_Debit_card_fraud_data.csv')